- funniture/src/main/java/com/ohgiraffers/funniture/config/BeanConfig.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/Inquiry.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryMapper.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/InquiryDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/Product.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ProductDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/response/Message.java
- funniture/src/main/java/com/ohgiraffers/funniture/response/ResponseMessage.java
BeanConfig 추가 / product 쪽 주석해야 run 실행됨
> :white_check_mark: 더미 문의 데이터 전체 조회하기 연습

- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/Rental.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalMapper.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/PostAddressDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/RentalDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/RentalOptionInfoDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
- funniture/src/main/resources/mapper/rental/RentalMapper.xml
rental Controller, Service, Mapper, DTO, Entity, Mapper.xml 추가
> :art: rental Controller, Service, Mapper, DTO, Entity, Mapper.xml 추가

- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/CategoryDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/MemberDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/OwnerInfoDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/RentalDTO.java
- funniture/src/main/resources/mappers/rental/RentalMapper.xml
findRentalAllListByAdmin 에서 조회해 올 데이터가 더 필요하여 xml 파일 수정(join),
MemberDTO, RentalDTO, CategoryDTO,  OwnerInfoDTO 수정 및 추가
> :recycle:feature/findRentalAllListByAdmin_modify_eunmi

- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/RentalEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/RentalInfo.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalRepository.java
> 충돌 해결을 위한 push

- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/Inquiry.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
-  inquiry(문의) [조회 / 수정 / 삭제 / 등록]  완료
- inquiry_no 신규 등록 시 마다 자동 생성 완료 (INQ001 , INQ002 ..... INQ016)
> :sparkles: inquiry(문의) [조회 / 수정 / 삭제 / 등록] / inquiry_no

- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductDetailEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/RentalOptionInfoEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductDetailRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ProductDetailDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
상품 등록,ProductDTO 분리
null에대한 기본값 적용 연구 예정
ProductDTO, ProductDetailDTO(rental info + category) 분리
> :sparkles: 상품 등록, :recycle: ProductDTO 분리

- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ProductWithPriceDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
product 를 기준으로 join해서 컬럼을 가져오는 방법을 추가해뒀습니다.
>  :memo: join select 은미님 참고 자료 :memo:

- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductDetailEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductWithPriceEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/RentalOptionInfoEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductWithPriceRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ProductWithPriceDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
join 해서 특정 데이터만 가져오는 경우에 대해서 코드 구조 변경해뒀습니다.
select만 하실 경우에는 제가 해둔 방법으로 해도 상관 없지만
insert, update, delete  등과 같이 반영되야하는 작업을 하실 예정이시라면 제가 한것 처럼 entity에 일반 필드를 넣는 것이 아니라
연관관계를 설정하여 entity를 생성하고 그 데이터를 DTO 형태에 맞춰서 넣는 방식으로 바꿔야합니다.
> :art: 코드 구조 변경 :art:

- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductWithOptionEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductDetailRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ProductDetailDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
@RequestParam(required = false) String ownerNo를 추가하여 제공자ID를 이용한 상품 리스트 조회가 가능합니다.
조회된 상품이 없다면 204에러로 등록된 상품이 없습니다. 가 msg로 들어가게 해뒀습니다.
ex)
/api/v1/prodct?ownerNo=MEM001
현재 제공자 & 카테고리를 동시에 적용하는 검색은 추가 예정입니다.
> Feature/product byowner yejin [제공자별 상품 조회 추가]

- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminCategoryEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminOwnerInfoEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminProductEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminRentalEntity.java
> :sparkles: admin-select-Entity 추가

- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/UserProductEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/UserRentalEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/UserRentalOptionInfoEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/UserOrderViewDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
사용자 주문/배송 조회 Rest-API 추가 @GetMapping("/api/v1/rental/user/orderList")
- 엔티티 추가
- DTO 추가
- 레파지토리 추가
> :sparkles: 사용자 주문/배송 조회 Rest-API 추가

- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductDetailRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
product 조회 기능 중 제공자별 검색 및 상품 상세정보 검색 service 분리
> :art: productService 구조 변경 :art:

- funniture/build.gradle
- funniture/src/main/java/com/ohgiraffers/funniture/config/QuerydslConfig.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminOwnerInfoEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminProductEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminRentalEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminRentalRepositoryCustom.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminRentalRepositoryCustomImpl.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/AdminRentalSearchCriteria.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
- QueryDSL 을 사용하여 조건별 조회 및 전체조회 기능 구현
- build.gradle dependencies 추가
- config.QuerydslConfig 추가
- AdminRentalRepositoryCustomImpl Class 추가
- AdminRentalRepositoryCustom Interface 추가
- AdminRentalSearchCriteria DTO 추가
> :sparkles:250202 관리자 예약 조건별 조회 및 전체조회_eunmi

- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/OwnerController.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/Inquiry.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/Member.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/Product.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/InquiryDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/MemberDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
- 제공자 id 별로 나누어야 하는데, 매개변수로 받아서 작업을 해야할지, 나중에 권한별로 구분을 할지 검토 필요
- 어찌 저찌 엔티티 3개 조인으로 조회는 가능하나, 기존에 구현해 놓은 수정(build로 구현)한 로직 에러 발생
- 내일 수정 예정
> :sparkles: 제공자 페이지의 문의 조회 (product , inquiry , member) 조인 / 하지만 검토가 필요함.

- funniture/build.gradle
- funniture/src/main/java/com/ohgiraffers/funniture/common/ProductSearchCondition.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/Inquiry.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/Product.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductWithPriceEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/RentalOptionInfoEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductWithPriceRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/productWithPriceDSL.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ProductDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminOwnerInfoEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminRentalEntity.java
#52 
product 의 검색 조건이 다양한것에 대해서 동적 쿼리문 사용을 위해 queryDSL을 사용하여 조회 방식을 변경하였다.
또한 현재까지 작성된 api들의 swager를 작성하며 vaildation 등의 예외처리를 추가했다.
Swagger
Postman
> ⚡[ PR ] 2025/2/12 product 구조 dsl로 변경 및 swagger 작성 🎨

- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
> merge 5 : InquiryService 수정

- funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
#51 
- 최종  merge 6 / MemberEntity 필드 맞춰줌. 에러 수정
- 멤버 패키지 생성 (패키지 분리)
- 제공자 번호로 전체 상품에 대한 문의 조회 완료 
> :recycle: :bug: 멤버 패키지 생성 / 제공자 번호로 전체 상품에 대한 문의 조회

- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepositoryCustomImpl.java
> :green_heart:[PR]2025/02/12 Swagger 추가-정은미:green_heart:

- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
#51 
- 문의(Inquiry) Rest_API 작성
> 💚 [PR]2025/02/12 문의 Rest_API(Swagger) 작성-김규남💚

- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepositoryCustom.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepositoryCustomImpl.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
> :sparkles:[PR]2025/02/13 사용자별 예약조회-정은미:sparkles:

- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/InquiryRegistEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/RegistRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/InquiryDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/OwnerInquiryDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
#66 
#65
- Rest API 설계 작성 도중,  DTO 및 엔티티 생성
> :wrench: [PR]2025/02/13 DTO 및 엔티티 생성 -김규남 :wrench:

- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
#65 
#66 
- regist 레파지토리 생성
- member dto → member 패키지로 이동
- 전체 로직 테스트 진행 (이상 없음)
> :wrench: [PR]2025/02/13 Rest-api 설계 테스트 및 파일 구조 변경-김규남 :truck:

- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/RentalDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
예약 등록 수정 
- DTO 수정
- 예약진행상태 예약대기로 자동 등록되게 set
응답데이터 
- 응답 메세지 수정
- swagger 수정
> :art:[PR]2025/02/12 예약등록&응답데이터&swagger 수정-정은미:art:

- funniture/build.gradle
- funniture/src/main/java/com/ohgiraffers/funniture/config/webSecurityConfig.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/InquiryEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/InquiryDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AuthController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/MemberRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberRoleDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AuthService.java
#78 
#77 
- 회원가입 구현 중, 충돌 우려로 중간 커밋 진행
> ✨[PR]2025/02/14 스프링 시큐리티 회원가입 - 중간 커밋 -김규남 ✨

- funniture/src/main/java/com/ohgiraffers/funniture/config/webSecurityConfig.java
#77 
#78 
- 스프링 시큐리티 - postman을 이용하여 회원가입 insert 완료
- member_id 자동 생성
- encoder로 비밀번호 암호화 완료
> ✨[PR]2025/02/14 회원가입(encoder / postman 이용) - 김규남✨

- funniture/build.gradle
- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/CustomAuthenticationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/HeaderFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthFailUserHandler.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthSuccessHandler.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthenticationProvider.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/interceptor/JwtTokenInterceptor.java
- funniture/src/main/java/com/ohgiraffers/funniture/common/AuthConstants.java
- funniture/src/main/java/com/ohgiraffers/funniture/config/webSecurityConfig.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/TokenDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/CustomUserDetailsService.java
- funniture/src/main/java/com/ohgiraffers/funniture/util/ConvertUtil.java
- funniture/src/main/java/com/ohgiraffers/funniture/util/TokenUtils.java
- funniture/src/main/resources/application.yml
#77 
#85 
- 로그인을 위한 spring 시큐리티 설정
-  jwt 토큰 설정
- 일단 구조만 구성해 놓고, 앞으로 검증 예정
> :truck: 📝 [PR]2025/02/14 로그인을 위한 spring 시큐리티 설정 및 jwt 토큰 설정 -김규남 📝 :truck:

- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
#90 
카테고리별 제공자 조회 + DSL이 아닌 단순 JPQL로 변경
=> 동적 쿼리문이 아닌 조건이 변경되는 구조이기 때문에 JPQL 사용
> :zap: [PR] 2025/2/15 카테고리별 제공자 조회 추가 및 수정 [정예진] :zap:

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/CustomAuthenticationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthSuccessHandler.java
- funniture/src/main/java/com/ohgiraffers/funniture/config/WebConfig.java
- funniture/src/main/java/com/ohgiraffers/funniture/config/WebSecurityConfig.java
#88 
#92 
- 로그인 구현 중, postman으로 요청 보낼 시 403에러 발생 했으나, 200 응답 완료
- 추가 구현 예정
> 🐛✨ [PR]2025/02/16 postman을 이용한 로그인 검증 -김규남 🐛✨

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
#88 
#92 
- 로그인 기능 구현 중, 작업을 위한 접근 권한 설정
> :ambulance: 긴급 : 접근 권한 수정 :ambulance:

- funniture/http/productRestAPI.http
- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/CustomAuthenticationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthFailUserHandler.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthSuccessHandler.java
- funniture/src/main/java/com/ohgiraffers/funniture/config/WebSecurityConfig.java
- funniture/src/main/java/com/ohgiraffers/funniture/exception/ApiExceptionAdvice.java
- funniture/src/main/java/com/ohgiraffers/funniture/exception/DuplicatedMemberEmailException.java
- funniture/src/main/java/com/ohgiraffers/funniture/exception/LoginFailedException.java
- funniture/src/main/java/com/ohgiraffers/funniture/exception/TokenException.java
- funniture/src/main/java/com/ohgiraffers/funniture/exception/dto/ApiExceptionDTO.java
#88 
#92 
- 아직 postman을 이용하여 로그인 검증중
- 검증을 위한 파일 추가 및 수정
> 🎨 [PR]2025/02/16 로그인 로직 구현중, 파일 추가 및 수정 -김규남  🚚

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/CustomAuthenticationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthSuccessHandler.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthenticationProvider.java
- funniture/src/main/java/com/ohgiraffers/funniture/config/WebSecurityConfig.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/CustomUserDetailsService.java
- funniture/src/main/java/com/ohgiraffers/funniture/util/TokenUtils.java
#88 
#92 
- 로그인 구현 테스트중. 
-  토큰 생성이 되지 않고 있어서 출력구문 찍고 분석중
> 📝[PR]2025/02/16 로그인 구현중 (충돌 날까봐 중간 머지) - 김규남 :white_check_mark:

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/CustomAuthenticationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/interceptor/JwtTokenInterceptor.java
- funniture/src/main/java/com/ohgiraffers/funniture/config/WebSecurityConfig.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AuthService.java
- funniture/src/main/java/com/ohgiraffers/funniture/util/TokenUtils.java
#88 
#92 
<회원 가입>
- 기존 : member엔티티의 대부분의 값을 이용하여 회원가입
- 변경 : 실제 사용자가 입력한 값만 받아 회원 가입
<로그인>
- 진행중
> :art: [PR]2025/02/16 회원가입 시 필요한 값들로만 수정- 김규남 (email , password, userName) :art:

- funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/controllers/DeliveryAddressController.java
- funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/entity/DeliveryAddressEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminRentalRepositoryCustomImpl.java
#100 
- 배송지 조회 => 스웨거 추가
- 주문번호 검색 => 정확히 일치하지 않고, 포함될 때도 검색 가능하게 변경 (관리자 예약 검색조건 필터링)
> :green_heart:[PR]2025/02/17 deliveryaddress 스웨거 추가&관리자 검색조건 rentalNo 수정-정은미:art:

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/CustomAuthenticationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthSuccessHandler.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthenticationProvider.java
- funniture/src/main/java/com/ohgiraffers/funniture/config/WebSecurityConfig.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/MemberRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/CustomUserDetailsService.java
#98 
#99 
- postman을 이용하여 로그인 완료 (토큰 정보 반환)
> ✨[PR]2025/02/17 postman을 이용하여 로그인 완료 (토큰 정보 반환) - 김규남✨

- funniture/src/main/java/com/ohgiraffers/funniture/common/ProductSearchCondition.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/MemberRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/CustomUserDetailsService.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/productWithPriceDSL.java
#103 
판매 상태에 따른 제품 검색 추가
전체 업체 리스트 조회 완성
> ✨ [PR] 2025/2/17 제품 검색 조건 판매 상태 추가 + 전체 업체 조회 추가 [정예진] ✨

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/HeaderFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/config/WebSecurityConfig.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AuthController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/MemberRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AuthService.java
#98 
- 프론트-백엔드 로그인 연결
- 로그인 시 메인 페이지 이동
- 중복 체크 , 유효성 검증은 이후 예정
> ✨[PR]2025/02/17 프론트-백엔드 로그인 연결 - 김규남✨

- funniture/src/main/java/com/ohgiraffers/funniture/auth/handler/CustomAuthSuccessHandler.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/TokenDTO.java
#109 
#110 
- 프론트에서 사용할 id, role 정보 추가하여 전달
> ✨[PR]2025/02/18 프론트에 전달할 id, role 정보 삽입 - 김규남✨

- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ChangeStatusDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
#112 
PUT 을 이용한
상품 상태 정보 수정 API 생성 및 연결 완료
> :sparkles: 상품 상태 정보 수정 완료 :sparkles:

- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductForDeleteRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
#112 
상품 삭제 시도 중인데 상품을 삭제하면 일이 커짐(연관된게 많음)
상품 삭제시, 해당 상품 문의와 리뷰만 삭제할까?
> 🔀 [PR] 2025/2/18 merge용 [정예진] 🔀

- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AuthController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
#123 
#117 
- 문의 / 회원가입 / 로그인 swagger 및 restAPI 추가
> 💚[PR]2025/02/19 문의 / 회원가입 / 로그인 swagger 추가 - 김규남💚

- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AuthController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
#117 
#123 
- 문의 / 회원가입 / 로그인 swagger 및 restAPI 수정!
> 💚[PR]2025/02/19 문의 / 회원가입 / 로그인 swagger 수정 - 김규남💚

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
- 사용자 예약번호 자동생성 수정 
- jwt -> "/api/v1/rental/regist" 추가
> :art:[PR]2025/02/19 사용자 예약등록 rentalNo 자동생성 부분 수정 및 Jwt 추가 - 정은미:art:

- funniture/src/main/java/com/ohgiraffers/funniture/member/entity/OwnerInfoEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/productWithPriceDSL.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminProductEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminRentalRepositoryCustomImpl.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/RentalDetailDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
- OwnerInfoEntity Member 로 파일 위치 변경
> :truck:[PR]2025/02/20 OwnerInfoEntity Member 로 파일 위치 변경 - 정은미:truck:

- funniture/build.gradle
- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/config/MailConfig.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AuthController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MailController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MailService.java
- funniture/src/main/resources/application.yml
#129 
- postman으로 이메일 요청 시, gmail로 이메일 보내기 완료.
> ✨[PR]2025/02/20 이메일 요청 시, gmail로 인증 번호 발송 - 김규남 ✨

- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/OwnerInfoDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductDetailEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductDetailRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ProductDetailDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
#134 
productDetail 조회 내역 추가
제공자 정보도 죄회 될 수 있도록 수정
> :art: [PR] 2025/02/20 productDetail 조회 내역 추가 -정예진 :art:

- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MailController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
#139 
#140 
- 로그인 페이지에서 비밀번호 찾기 (변경) 하기 완료
> ✨[PR]2025/02/21 로그인 페이지 비밀번호 변경 - 김규남✨

- funniture/build.gradle
- funniture/src/main/java/com/ohgiraffers/funniture/cloudinary/CloudinaryService.java
- funniture/src/main/java/com/ohgiraffers/funniture/config/CloudinaryConfig.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductDetailEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductWithOptionEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductWithPriceEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/ProductDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
- funniture/src/main/resources/application.yml
#120 #142 
상품 등록 프론트, 백 및 cloudnary 연결하여 이미지 업로드
> :sparkles: [PR] 2025/02/21 상품 등록 + 이미지 cloudinary 업로드 - 정예진 :sparkles:

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
#148 
#152 
#151 
- 사용자 마이 페이지에서 전화번호 불러오기 로직
- 사용자 마이 페이지에서 전화번호 변경하기 로직
> ✨[PR]2025/02/23 사용자 마이 페이지 정보 변경 및 불러오기 - 김규남✨

- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
#163 
#165 
- 사용자 마이페이지에서 주소 변경 로직 구현
> ✨[PR]2025/02/24 사용자 마이페이지에서 주소 변경 로직 / api 작성 - 김규남 ✨

- funniture/src/main/java/com/ohgiraffers/funniture/common/PagingButton.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/RentalOptionInfoRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
> :sparkles: [PR] 2025/02/25 상품 등록 예외처리 및 완성 - 정예진 :sparkles:

- funniture/src/main/java/com/ohgiraffers/funniture/point/controllers/PointController.java
- funniture/src/main/java/com/ohgiraffers/funniture/point/model/dao/PointRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/point/model/service/PointService.java
> :twisted_rightwards_arrows: PointController 소스트리에서 잘못 삭제함 - 정은미:twisted_rightwards_arrows:

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/point/controllers/PointController.java
- funniture/src/main/java/com/ohgiraffers/funniture/point/model/dao/PointRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/point/model/dto/PointDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/point/model/service/PointService.java
#175
- 포인트 사용, 충전 내역 조회 API
- 스웨거 추가
- doFilterInternal 에 API 경로 추가
> :sparkles:[PR]2025/02/24 포인트 사용, 충전 내역 조회 API, 스웨거 추가 - 정은미:green_heart:

- funniture/src/main/java/com/ohgiraffers/funniture/point/entity/PointEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
> :art:[PR]2025/02/25 상품 등록 API 수정 -정은미:art:

- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
#193
- 제공자별 예약 내역 조회 API 수정
- 스웨거 수정
> :art:[PR]2025/02/26 제공자별 예약 내역 조회 API, 스웨거 수정 - 정은미:green_heart:

- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalRepositoryCustom.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalRepositoryCustomImpl.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
#194 
- 제공자별 예약조회 API 수정(예약, 배송, 반납 탭별로 필터링) 
- 스웨거 수정
> :art:[PR]2025/02/26 제공자별 예약조회 API(예약, 배송, 반납 탭별로 필터링), 스웨거 수정-정은미:green_heart:

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberAndPointEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/entity/OwnerInfoEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/MemberRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberAndPointDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/OwnerInfoDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/PointDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
#198 
- 관리자 페이지에서 유저 항목에 필요한 데이터 로직 
> 🌐 [PR]2025/02/26 관리자 페이지에 필요한 데이터 연결 - 김규남 🌐

- funniture/src/main/java/com/ohgiraffers/funniture/common/OrderByNull.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/ProductDetailEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/entity/RentalOptionInfoEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductWithPriceRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/productWithPriceDSL.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dto/RecentProductDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
#201 
최근 본 상품의 간단한 데이터 목록 조회를 위한 api 추가
> :sparkles: [PR] 2025/02/26 최근 본 상품 완료 - 정예진 :sparkles:

- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberAndPointEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/entity/OwnerInfoEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberAndPointDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberRoleDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/OwnerInfoAndMemberDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
#198 
- 관리자 페이지에서 모든 제공자 및 사용자 정보 불러오기
> ✨[PR]2025/02/26 관리자 페이지에서 모든 제공자 및 회원 불러오기 - 김규남✨

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/favorite/controller/FavoriteController.java
- funniture/src/main/java/com/ohgiraffers/funniture/favorite/entity/FavoriteCombinedKey.java
- funniture/src/main/java/com/ohgiraffers/funniture/favorite/entity/FavoriteEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dao/FavoriteDSL.java
- funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dao/FavoriteRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dto/FavoriteDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/service/FavoriteService.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/model/service/ProductService.java
> ✨ [PR] 2025/02/26 관심상품 조회 완성 - 정예진 ✨

- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/entity/OwnerInfoEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/OwnerRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/AppOwnerInfoDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
#192 
#195 
- 프론트에서 신청과 동시에 데이터 전송  및 처리 로직 
- 조금 더 수정 해야 함.
> ✨[PR]2025/02/26 마이페이지 제공자 신청 로직 -김규남✨

- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberAndPointEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/AppOwnerListDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
#207 
#208 
- 제공자 전환 데이터 불러와서 프론트 전달
> 🌐✨[PR]2025/02/27 제공자 전환 데이터 불러오기 - 김규남✨🌐

- funniture/src/main/java/com/ohgiraffers/funniture/cloudinary/CloudinaryService.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/entity/OwnerInfoEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/AppOwnerInfoDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberAndPointDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
#207 
#211
- 마이페이지에서 제공자 전환 신청 시 데이터 저장
- image / pdf는 클라우디너리 통하여 url로 저장
> ✨[PR]2025/02/27 사용자 - 제공자 전환 신청 시 데이터 삽입 (image, pdf) - 김규남✨

- funniture/src/main/java/com/ohgiraffers/funniture/favorite/controller/FavoriteController.java
- funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dao/FavoriteDetailInfoDSL.java
- funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dao/FavoriteDetailInfoRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dao/FavoriteListRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dto/FavoriteDetailInfoDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dto/FavoriteListDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/service/FavoriteService.java
#216 
- 관심 상품 기존 DB에 내역과 비교하여 추가 또는 삭제하는 /favorite/update API 생성
- 상품의 리스트만 조회 또는 상품의 상세 정보를 조회하는 API 분리
> :sparkles: [PR] 2025/02/27 관심상품 전체 완료 - 정예진 :sparkles:

- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AuthController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AuthService.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
#207 
#208 
#211 
- 제공자 전환 신청 및 재신청 로직 
> ✨[PR]2025/02/27 제공자 전환 신청 / 재신청 로직 - 김규남✨

- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/AppOwnerListModalDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/OwnerInfoDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
#208 
#207 
- 제공자 전환 재신청 로직
- 관리자 페이지 제공자 전환 신청 / 재신청 데이터 불러오기
- [x ] 새 API 추가
> ✨[PR]2025/02/27 관리자 페이지에 필요한 데이터 로직 - 김규남✨

- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepositoryCustom.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepositoryCustomImpl.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
> :art:[PR]2025/03/01 사용자별 주문 조회 페이징 처리 적용 - 정은미:art:

- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminRentalRepositoryCustom.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminRentalRepositoryCustomImpl.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
> :art:[PR]2025/03/01 관리자 예약정보 조회 페이징 처리 적용 - 정은미:art:

- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
> :green_heart:[PR]2025/03/01 관리자 예약정보, 제공자별 예약, 사용자별 주문 조회 Swagger 수정 - 정은미:green_heart:

- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberAndPointDTO.java
#225 
#235 
- 관리자 페이지, 사용자에서 탈퇴자 다중 권한 변경 로직
> 🌐✨[PR]2025/03/02 사용자 - 탈퇴자 권한 변경 쿼리 수정 - 김규남 ✨🌐

- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/DetailRentalEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/DetailRentalRepositoryCustomImpl.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/RentalDetailDTO.java
#238
- 주문별 상세페이지 API 수정(대여자 정보 추가) 
> :art:[PR]2025/03/02 주문별 상세페이지 API 수정(대여자 정보 추가) - 정은미:art:

- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberAndPointEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/OwnerInfoDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MailService.java
#225 
#237 
- 제공자 전환 신청자 반려 / 승인 로직
- 승인 시 제공자 탭으로 이동 / 반려 시 사용자 탭으로 이동
- tbl_member  반려사유 컬럼 추가 
> 🌐✨[PR]2025/03/02 제공자 전환 신청 반려 / 승인 - 김규남✨🌐

- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalRepositoryCustom.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalRepositoryCustomImpl.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/OwnerRentalViewDTO.java
#241
- 제공자별 조회 API 수정(주문 상세페이지와 연결하기 위해 예약데이터 추가)
> :art:[PR]2025/03/02 제공자별 조회 API 수정 - 정은미:art:

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/RejectedMessageDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
#225 
- 제공자 전환 신청 후, 심사 텍스트 출력 / 재신청 연결중
> 🌐✨[PR]2025/03/02 제공자 전환 신청 후, 심사 텍스트 출력 / 재신청 연결중  - 김규남 ✨🌐

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/RentalEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
> :sparkles:[PR]2025/03/02 예약대기 -> 예약완료로 상태 update - 정은미:sparkles:

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/RentalEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalRepositoryCustomImpl.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
#256
- 운송장번호, 운송업체명, 예약진행상태 수정
> :sparkles:[PR]2025/03/03 운송장번호, 운송업체명, 예약진행상태 수정 - 정은미:sparkles:

- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberAndPointDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/PointUpdateDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
#225 
#258
- 관리자 페이지 상세 정보 출력
- 유저 포인트 수정 로직 추가
- 제공자 전환 , 승인 / 반려에 따른 데이터 이동 수정
> ✨[PR]2025/03/03 관리자 페이지 상세 정보 출력 - 김규남 ✨

- funniture/src/main/java/com/ohgiraffers/funniture/chat/controller/ChatController.java
- funniture/src/main/java/com/ohgiraffers/funniture/chat/model/service/ChatService.java
#250 
관리자 페이지 문의 목록 관리 프론트 & 백 연결
> :sparkles: [PR] 2025/03/04 관리자 페이지 질문 관리 백 & 프론트 연결 - 정예진 :sparkles:

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/OwnerRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
#263 
#260
마이 페이지, 제공자 전환 storeNo 중복 검사 로직 추가
> 🐛✨[PR]2025/03/04 제공자 전환 storeNo 중복 검사 로직 추가 - 김규남 ✨🐛

- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
#260 
- 관리자 페이지 유저 정보 불러오는 로직 수정
> 🚚 [PR]2025/03/04 관리자 페이지 유저 정보 불러오는 로직 수정 - 김규남  🚚

- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
#268 
#269 
- 관리자 페이지 페이징 처리 로직 추가
> 🌐✨[PR]2025/03/05 관리자 페이지 페이징 처리 로직 추가  - 김규남 ✨🌐

- funniture/src/main/java/com/ohgiraffers/funniture/chat/controller/ChatController.java
- funniture/src/main/java/com/ohgiraffers/funniture/chat/entity/ChatEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/chat/model/dao/BasicChatRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/chat/model/dao/ChatDSL.java
- funniture/src/main/java/com/ohgiraffers/funniture/chat/model/dto/ChatDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/chat/model/service/ChatService.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
#271 
관리자 페이지의 챗봇 질문에 대해서 수정 및 추가 완료 + 로그아웃 시 store user정보 삭제
> :sparkles: [PR] 2025/03/05 관리자 페이지 챗봇 질문 관리 수정, 등록 완료 - 정예진 :sparkles:

- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
- funniture/src/main/java/com/ohgiraffers/funniture/point/model/service/PointService.java
#277 
- 상담 중 여부 변경 백과 연결 완료
- 상담 중여부에 따른 user의 isconsulting 업데이트로 css변환
> ✨ [PR] 2025/03/05 상담중 여부 변경 완료 - 정예진 ✨

- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AuthService.java
- funniture/src/main/java/com/ohgiraffers/funniture/point/model/dao/PointRepository.java
#268 
#279 
- 회원 가입 시 포인트 100,000 점 등록
> ⚡️[PR]2025/03/05 회원가입 시 포인트 삽입 추가   -  김규남 ⚡️

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/InquiryEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/InquiryDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
#268 
#281 
- 상품별 문의 조회 로직 수정 및 연결
> 🌐[PR]2025/03/05 상품 별 문의 조회 로직 수정 및 연결 - 김규남 🌐

- funniture/src/main/java/com/ohgiraffers/funniture/point/model/dto/PointDTO.java
> :art:[PR]2025/03/06 포인트 내역 조회 수정 - 정은미:art:

- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/InquiryEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/InquiryDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
#286 
#285 
- 상품 문의 등록 
- 상품 별 문의 조회 로직 수정 
> ✨[PR]2025/03/06 상품 문의 등록 로직 / 불러오는 로직 수정 - 김규남 ✨

- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/OwnerInquiryDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
> 🌐✨[PR]2025/03/06 제공자 마이페이지 문의 연결 로직 - 김규남✨🌐

- funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java
- 필요없는 has_image 컬럼 삭제 
-  테스트 이상 없음
> 🐛 [PR]2025/03/06 has_image 삭제 - 김규남 🐛

- funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/controller/AdminInquiryController.java
- funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/entity/AdminInquiryEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/dao/AdminInquiryDSL.java
- funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/dao/AdminInquiryRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/dto/AdminInquiryDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/dto/ConsultingListDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/service/AdminInquiryService.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
#294 
관리자와의 1:1 문의에 사용자 리스트(문의 이력이 있는) 조회 출력 연결 완료
사용자별 문의 내역 조회 API완료
> ✨[PR] 2025/03/06 문의 사용자 목록 조회 - 정예진 ✨

- funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/controller/AdminInquiryController.java
- funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/dto/AdminInquiryDTO.java
사용자별 문의 내역 출력을 보낸거 받은거 따로해서 프론트에 보냈었는데
전체 시간순으로 나열해야하기 때문에 api 반환 데이터 분리 안한걸로 변경
> :zap: [PR] 2025/03/06 코드 수정 - 정예진 :zap:

- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserActiveRentalRepositoryCustomImpl.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
> :art:[PR]2025/03/07 배송지 수정 API update - 정은미:art:

- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
> 🌐✨[PR]2025/03/07 제공자 문의 페이지 페이징 처리 로직 - 김규남✨🌐

- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/RentalEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
#307
- 사용날짜,만료날짜 수정되게 예약진행상태 API 수정 
> :art:[PR]2025/03/07 사용날짜,만료날짜 수정되게 예약진행상태 API 수정 -정은미:art:

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/controllers/ReviewController.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/entity/ReviewEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/model/dao/ReviewRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/model/dto/ReviewRegistDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/model/service/ReviewService.java
#301 
#310 
- 리뷰 등록 로직 구성 / API 작업 
- DTO, ENTITY, SERVICE, REPOSITOY, CONTROLLER 전체 생성
> ✨[PR]2025/03/08 리뷰 등록 로직 구현 - 김규남✨

- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/controllers/ReviewController.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/entity/ReviewEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/model/dao/ReviewRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/model/dto/ReviewDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/model/service/ReviewService.java
#301 
#312 
- 사용자 리뷰 페이지 조회 로직 구현
- 페이징 처리 로직
> 🌐✨[PR]2025/03/08 사용자 리뷰 페이지 조회 및 페이징 로직 -김규남 ✨🌐

- funniture/src/main/java/com/ohgiraffers/funniture/review/controllers/ReviewController.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/entity/ReviewEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/model/dao/ReviewRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/model/dto/ReviewProductDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/model/service/ReviewService.java
#301 
#314 
- 리뷰 데이터 제품 상세페이지 연결
> 🌐✨[PR]2025/03/08 리뷰 데이터 제품 상세페이지 연결 - 김규남 ✨🌐

- funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/controller/AdminInquiryController.java
- funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/entity/AdminInquiryEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/dao/AdminInquiryRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/dto/ConsultingListDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/model/service/AdminInquiryService.java
#317 
관리자 1:1 문의 완성 및 마지막 보낸사람이 누군지 확인하기 위해 기존 API 수정
> :sparkles: [PR] 2025/03/08 1:1문의 완성 - 정예진 :sparkles:

- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/productWithPriceDSL.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/entity/AdminSalesEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminSalesRepositoryCustom.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminSalesRepositoryCustomImpl.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/AdminSalesDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
> :sparkles:[PR]2025/03/09 관리자페이지 매출현황 조회 API - 정은미:sparkles:

- funniture/src/main/java/com/ohgiraffers/funniture/adminInquiry/controller/AdminInquiryController.java
- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/notice/controller/NoticeController.java
- funniture/src/main/java/com/ohgiraffers/funniture/notice/entity/NoticeEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/notice/model/dao/NoticeRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/notice/model/dto/NoticeDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/notice/model/service/NoticeService.java
- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
> ✨ [PR] 2024/03/09 공지사항 조회, 등록, 삭제 - 정예진 ✨

- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AuthService.java
- 회원 가입 시, is_consulting이 null로 삽입되어 에러 발생하던 거 수정
> 🐛[PR]2025/03/09 회원 가입 시 is_consulting 에러 수정  - 김규남 🐛

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/OwnerController.java
- funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/OwnerInfoService.java
#324 
- 업체 정보 조회 API 생성
- 업체정보 조회 백 프론트 연결
> :sparkles: [PR] 2025/03/09 제공자 업체정보 페이지 완성 - 정예진 :sparkles:

- funniture/src/main/java/com/ohgiraffers/funniture/review/controllers/ReviewController.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/model/dao/ReviewRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/model/dto/OwnerReviewDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/model/service/ReviewService.java
#301 
#323 
- 제공자 메인 페이지  , 제공자 리뷰 페이지 리뷰 데이터 연결
- 페이징 처리
> 🌐✨[PR]2025/03/09 제공자 메인 페이지 / 리뷰 페이지 연결 - 김규남✨🌐

- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminSalesRepositoryCustom.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminSalesRepositoryCustomImpl.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerSalesRepositoryCustom.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerSalesRepositoryCustomIpml.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/AdminSalesDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/OwnerSalesDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/RentalChartDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
> :sparkles:[PR]2025/03/09 제공자별 월별 매출 현황 조회 API - 정은미:sparkles:

- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerSalesRepositoryCustomIpml.java
#329 
제공자별 월별 정산관리 조회 예약번호 오름차순 추가
> :art:[PR]2025/03/10 제공자별 월별 정산관리 조회 예약번호 오름차순 추가 - 정은미:art:

- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/controllers/ReviewController.java
#301 
- 사용자 페이지 리뷰 등록 로직 및 쿼리 수정
> 🌐✨[PR]2025/03/10 사용자 페이지 리뷰 등록 로직 및 쿼리 수정 - 김규남 ✨🌐

- funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
- funniture/src/main/java/com/ohgiraffers/funniture/comment/controllers/CommentController.java
- funniture/src/main/java/com/ohgiraffers/funniture/comment/entity/CommentEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/comment/model/dao/CommentRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/comment/model/dto/CommentRegistDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/comment/model/service/CommentService.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/entity/InquiryEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/OwnerInquiryDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/controllers/ReviewController.java
#335
#301 
- 제공자 페이지, 문의 답변 로직 구성
- 답변 완료 / 답변 대기 구분
> 🌐✨[PR]2025/03/10  문의 답변 로직 - 김규남 ✨🌐

- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerSalesRepositoryCustomIpml.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
#338
-  예약 등록 시 할인율 적용 된 포인트 금액 차감& 포인트적립 수정
> :art:[PR]2025/03/10 예약 등록 시 할인율 적용 된 포인트 금액 차감& 포인트적립 수정 - 정은미:art:

- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminSalesRepositoryCustomImpl.java
#340
- 관리자 정산 그룹화 수정 (날짜형식, 대여기간별 조건 제거)
> :art:[PR]2025/03/10 관리자 정산 그룹화 수정 - 정은미:art:

- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerCurrentMonthSalesRepositoryCustom.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerCurrentMonthSalesRepositoryCustomImpl.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerMonthlySalesRepositoryCustom.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerMonthlySalesRepositoryCustomImpl.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/SalesRepositoryCustom.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/SalesRepositoryCustomImpl.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalRepositoryCustomImpl.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/AdminMonthlySalesDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/CurrentMonthSalesDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/MonthlySalesDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/UserOrderViewDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
#344
- 제공자/관리자 마이페이지 메인 차트 데이터 API
관리자 메인 차트 (일별/월별)
제공자별 이번 달 매출 조회(상품별 합산)
제공자별 월별 매출 조회(상품전체 합산)
> :sparkles:[PR]2025/03/11 제공자/관리자 마이페이지 메인 차트 데이터 - 정은미:sparkles:

- funniture/src/main/java/com/ohgiraffers/funniture/product/model/dao/ProductRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
#346
- 반납완료로 상태 업데이트 시 used_stock 예약갯수에 따라 감소
> :art:[PR]2025/03/11 반납완료로 상태 업데이트 시 used_stock 예약갯수에 따라 감소 - 정은미:art:

- funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
> :bug: [PR] 2025/03/11 응답 상태코드 변경 - 정예진 :bug:

- funniture/src/main/java/com/ohgiraffers/funniture/comment/controllers/CommentController.java
- funniture/src/main/java/com/ohgiraffers/funniture/comment/model/dao/CommentRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/comment/model/dto/CommentByMyPageDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/comment/model/service/CommentService.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/MemberInquiryDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalRepository.java
#351 
- 제공자 문의 답변에 따른 사용자 페이지 연결
- 모달 상세 보기 로직
- 리뷰 쿼리 수정 (예약완료 → 배송완료, 반납요청, 수거중, 반납완료) 데이터 출력
> 🌐✨[PR]2025/03/11 제공자 문의 답변에 따른 사용자 페이지 연결 / 상세 보기 로직 / 리뷰 쿼리 수정 - 김규남 ✨🌐

- funniture/src/main/java/com/ohgiraffers/funniture/comment/controllers/CommentController.java
- funniture/src/main/java/com/ohgiraffers/funniture/comment/entity/CommentEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/comment/model/dao/CommentRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/comment/model/dto/CommentByProductDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/comment/model/service/CommentService.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/controllers/ReviewController.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/model/dao/ReviewRepository.java
#351 
-  제공자 문의 답변에 따른 상세페이지 연결 로직
>  🌐✨[PR]2025/03/11 제공자 문의 답변에 따른 상세페이지 연결 로직  -  김규남✨ 🌐

- funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/OwnerTopDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
> :sparkles:[PR]2025/03/12 업체 매출 TOP5 API - 정은미:sparkles:

- funniture/src/main/java/com/ohgiraffers/funniture/review/controllers/ReviewController.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/entity/ReviewEntity.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/model/dao/ReviewRepository.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/model/dto/ReviewAvgScoreDTO.java
- funniture/src/main/java/com/ohgiraffers/funniture/review/model/service/ReviewService.java
#360 
- 제공자 마이페이지 평균 리뷰 별점 조회 로직
> 🌐✨[PR]2025/03/12 제공자 마이페이지 평균 리뷰 별점 조회 로직 - 김규남✨🌐

- funniture/src/main/java/com/ohgiraffers/funniture/favorite/model/dao/FavoriteDetailInfoDSL.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java
- 찜 group by 추가
- 예약취소 시 포인트 반환 및 이벤트 포인트 반환 수정 
> :art:[PR]2025/03/12 찜 group by 추가&예약취소 시 포인트 반환 및 이벤트 포인트 반환 수정 - 정은미:art:

- funniture/src/main/java/com/ohgiraffers/funniture/point/model/dao/PointRepository.java
> :art:[PR]2025/03/13 예약취소 시 결제금,포인트적립금 반환 부분 수정 - 정은미:art:

- funniture/src/main/java/com/ohgiraffers/funniture/product/controllers/ProductController.java
> :memo: [PR] 2025/03/13 console 정리 - 정예진 :memo:

- funniture/Dockerfile
> 와아아아아아아아아아

- funniture/src/main/java/com/ohgiraffers/funniture/config/WebConfig.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalRepositoryCustomImpl.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/OwnerRentalViewDTO.java
> 제공자 예약 상세페이지 이미지 수정

- funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java
- funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/AdminSalesRepositoryCustomImpl.java
> 관리자 페이징처리 수정(전체카운트 수정)
