funniture-Project/funniture-be

funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/controllers/DeliveryAddressController.java
funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/entity/DeliveryAddressEntity.java
funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/dao/DeliveryAddressRepository.java
funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/dto/DeliveryAddressDTO.java
funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/service/DeliveryAddressService.java
funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java

#70 
사용자별 배송지 조회
- DeliveryAddressController 추가
- DeliveryAddressService 추가
- DeliveryAddressDTO 추가 
- DeliveryAddressEntity 추가

:sparkles:[PR]2025/02/13 사용자별 배송지 조회-정은미:sparkles:

---

funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalRepositoryCustom.java
funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalRepositoryCustomImpl.java
funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/OwnerRentalViewDTO.java
funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java

#106
제공자별 예약 조회&만료일 필터링
- User 예약조회 엔티티 재사용(조인 일치)
- OwnerRentalViewDTO 추가
- OwnerRentalRepositoryCustom 추가
- OwnerRentalRepositoryCustomImpl 추가

:sparkles: [PR]2025/02/17 제공자별 예약 조회&만료일 필터링-정은미:sparkles:

---

funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AuthController.java
funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java

#109 
#113 
- 로그인 한 정보에 대해 서버에서 가져오는 로직 구현
- api/v1/member/{memberId}

 ✨[PR]2025/02/18 로그인 한 유저의 대한 정보 가져오기 - 김규남✨

---

funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java

#121 
- 로그인 시, 서버에서 패스워드까지 프론트로 넘어갔는데, 패스워드 넘어가지 않게 수정

⚡️ PR]2025/02/19 로그인 시, 백에서 프론트로 비밀번호 전달되지 않게 수정  - 김규남 ⚡️

---

funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/MemberRepository.java
funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java

#150 
#148 
- 사용자 마이페이지 비밀번호 인증
- 사용자의 입력 패스워드와 인코드 형태로 저장돼있는 패스워드 비교하여 리턴
- passwordEncoder.matches 사용

✨[PR]2025/02/23 사용자 마이페이지 비밀번호 인증 - 김규남 ✨

---

funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/controllers/DeliveryAddressController.java
funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/entity/DeliveryAddressEntity.java
funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/dao/DeliveryAddressRepository.java
funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/dto/DeliveryAddressDTO.java
funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/service/DeliveryAddressService.java

#156 , #155 
- 배송지 수정 API 추가 
- 스웨거 추가
- 사용자가 신규 배송지 등록 시 기본배송지(true)로 선택하면서 등록한다면 
원래 사용자의 기본배송지였던 것을 false 로 save 후 신규 배송지를 기본배송지로 등록되게 수정
=> 배송지 수정 기능을 하면서 기본배송지 문제를 확인하여 pr 수정, 등록 기능 구분 못했습니다..!ㅜ
- doFilterInternal 에 경로 추가

:sparkles:[PR]2025/02/23 배송지 수정 기능 , 스웨거 추가 및 배송지 등록 수정 - 정은미:art:

---

funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/controllers/DeliveryAddressController.java
funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/entity/DeliveryAddressEntity.java
funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/dao/DeliveryAddressRepository.java
funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/dto/DeliveryAddressDTO.java
funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/service/DeliveryAddressService.java

#157 
- 사용자 배송지삭제 기능 (DeleteMapping X) 
=> 과거 예약내역에서 배송지가 확인 되어야하기 때문에 DB 삭제 X
- 사용자별 배송지 조회 조건 추가 
=> destination_status = "활성화" 만 조회
- 스웨거 추가

:sparkles:[PR]2025/02/23 배송지 삭제 기능 스웨거 추가 및 조회 수정 -정은미:art:

---

funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
funniture/src/main/java/com/ohgiraffers/funniture/point/controllers/PointControllers.java
funniture/src/main/java/com/ohgiraffers/funniture/point/entity/PointEntity.java
funniture/src/main/java/com/ohgiraffers/funniture/point/entity/PointHistoryEntity.java
funniture/src/main/java/com/ohgiraffers/funniture/point/model/dao/PointHistoryRepository.java
funniture/src/main/java/com/ohgiraffers/funniture/point/model/dao/PointRepository.java
funniture/src/main/java/com/ohgiraffers/funniture/point/model/dto/PointDTO.java
funniture/src/main/java/com/ohgiraffers/funniture/point/model/dto/PointHistoryDTO.java
funniture/src/main/java/com/ohgiraffers/funniture/point/model/service/PointService.java

:sparkles:[PR]2025/02/23 보유 포인트 조회 기능, 스웨거 추가 - 정은미:sparkles:

---

funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberEntity.java
funniture/src/main/java/com/ohgiraffers/funniture/member/model/dto/MemberDTO.java

#163 
#164 
- 사용자 마이 페이지에서 기본 주소 정보 불러오기
-  memberDTO / MemberEntity에 address 추가

✨[PR]2025/02/24 주소 정보 불러오기 위한 memberDTO / MemberEntity에 address 추가 - 김규남 ✨

---

funniture/package-lock.json
funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/controllers/DeliveryAddressController.java
funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/dao/DeliveryAddressRepository.java
funniture/src/main/java/com/ohgiraffers/funniture/deliveryaddress/model/service/DeliveryAddressService.java

#177
- 사용자별 기본 배송지 조회
- 스웨거 추가 

:sparkles:[PR]2025/02/24 사용자별 기본 배송지 조회, 스웨거 추가 -정은미:green_heart:

---

funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java
funniture/src/main/resources/application.yml

#163 
#166 
#167 
- 사용자 마이 페이지 이미지 불러오기
- 사용자 마이 페이지 이미지 저장 (클라우드너리)
- 토큰 유효 시간 12시간으로 변경

✨[PR]2025/02/24 이미지 변경 로직 / 토큰 시간 수정 - 김규남✨

---

funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java

#163 
#168 
- 마이페이지에서 회원 탈퇴 클릭 시, 탈퇴자로 권한 변경
- USER → LIMIT

✨[PR]2025/02/24 사용자 마이페이지 탈퇴자 권한 변경 - 규남 ✨

---

funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AuthController.java
funniture/src/main/java/com/ohgiraffers/funniture/member/controller/MemberController.java
funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AuthService.java

#183 
#184 
- 회원 가입 시, 이메일 중복 여부 체크 로직 완료

✨[PR]2025/02/25  회원가입 시 이메일 중복 여부 체크 - 규남 ✨

---

funniture/src/main/java/com/ohgiraffers/funniture/member/controller/OwnerController.java

✨[PR]2025/02/25 사용자에서 제공자 전환 등록 로직 - 김규남✨

---

funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
funniture/src/main/java/com/ohgiraffers/funniture/member/entity/MemberAndPointEntity.java
funniture/src/main/java/com/ohgiraffers/funniture/member/model/dao/AdminRepository.java
funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java
funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/MemberService.java

#221 
#222 
#223 
- 관리자 페이지에서 탈퇴자 권한 불러오기
- 관리자 페이지에서 탈퇴자 → 사용자 권한 변경 로직

🌐✨[PR]2025/02/28 관리자 페이지 권한 변경 로직 -  김규남 ✨🌐

---

funniture/src/main/java/com/ohgiraffers/funniture/member/controller/AdminController.java
funniture/src/main/java/com/ohgiraffers/funniture/member/model/service/AdminService.java

#221 
#223 
- 관리자 페이지에서 사용자 → 탈퇴자 권한 변경 로직

🌐✨[PR]2025/02/28 관리자 페이지 사용자 → 탈퇴자 권한 변경  - 김규남✨🌐

---

funniture/src/main/java/com/ohgiraffers/funniture/auth/filter/JwtAuthorizationFilter.java
funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/RentalRepository.java
funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java

#246
- 제공자 예약확정 다중선택 가능하게  API 수정

:art:[PR]2025/03/03 제공자 예약확정 API 수정 - 정은미:art:

---

funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalStateCountRepositoryCustom.java
funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/UserRentalStateCountRepositoryCustomImpl.java
funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dto/RentalStateCountDTO.java
funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java

#287
- 사용자 마이페이지 예약진행상태별 갯수 조회 API

:sparkles:[PR]2025/03/06 사용자 마이페이지 예약진행상태별 갯수 조회 API - 정은미:sparkles:

---

funniture/src/main/java/com/ohgiraffers/funniture/inquiry/controllers/InquiryController.java
funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dao/InquiryRepository.java
funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/dto/MemberInquiryDTO.java
funniture/src/main/java/com/ohgiraffers/funniture/inquiry/model/service/InquiryService.java

#305 
#285 
- 사용자 마이페이지 문의 데이터 불러오는 로직
- 페이징 로직 추가
- 포스트맨 검증

🌐✨[PR]2025/03/07 마이페이지 문의 데이터, 페이징 로직 완료  - 김규남 ✨🌐

---

funniture/src/main/java/com/ohgiraffers/funniture/rental/controllers/RentalController.java
funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalStateCountRepositoryCustom.java
funniture/src/main/java/com/ohgiraffers/funniture/rental/model/dao/OwnerRentalStateCountRepositoryCustomImpl.java
funniture/src/main/java/com/ohgiraffers/funniture/rental/model/service/RentalService.java

:sparkles:[PR]2025/03/11 제공자의 예약진행상태 카운트 API - 정은미:sparkles:
